name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm --filter app type-check

      - name: Lint
        run: pnpm --filter app lint

      - name: Format check
        run: cd app && prettier --check src/

      - name: Run tests
        run: pnpm --filter app test

      - name: Build application
        run: pnpm --filter app build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: app/dist/
          retention-days: 1

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features sqlite

      - name: Check formatting
        run: cargo fmt --check
        working-directory: backend

      - name: Run clippy
        run: cargo clippy -- -D warnings
        working-directory: backend

      - name: Type check
        run: cargo check
        working-directory: backend

      - name: Setup test database
        run: |
          touch mandarinpath.db
          sqlx migrate run --source migrations
        working-directory: backend
        env:
          DATABASE_URL: sqlite:./mandarinpath.db

      - name: Run tests
        run: cargo test
        working-directory: backend
        env:
          DATABASE_URL: sqlite:./mandarinpath.db

      - name: Build application
        run: cargo build --release
        working-directory: backend

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/target/release/mandarinpath-backend
          retention-days: 1

  e2e:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: app/dist/

      - name: Download backend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend/target/release/

      - name: Make backend binary executable
        run: chmod +x backend/target/release/mandarinpath-backend

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features sqlite

      - name: Setup test database
        run: |
          touch dev.db
          sqlx migrate run --source backend/migrations
        env:
          DATABASE_URL: sqlite:./dev.db

      - name: Install Playwright browsers
        run: pnpm --filter mandarinpath-e2e-tests install-deps

      - name: Run E2E tests
        run: pnpm --filter mandarinpath-e2e-tests test
        env:
          DATABASE_URL: sqlite:./dev.db
          FRONTEND_URL: http://localhost:5173
          PORT: 3001

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30