name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    needs: []  # Will run independently but can be changed to depend on frontend/backend jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features sqlite

      - name: Build frontend
        run: pnpm --filter app build

      - name: Build backend
        run: cargo build --release
        working-directory: backend

      - name: Setup test database
        run: |
          touch dev.db
          sqlx migrate run --source backend/migrations
        env:
          DATABASE_URL: sqlite:./dev.db

      - name: Install Playwright browsers
        run: pnpm --filter mandarinpath-e2e-tests install-deps

      - name: Run E2E tests
        run: pnpm --filter mandarinpath-e2e-tests test
        env:
          DATABASE_URL: sqlite:./dev.db
          FRONTEND_URL: http://localhost:5173
          PORT: 3001

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30